In [1]:
conda install numpy

Retrieving notices: ...working... DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/notices.json HTTP/1.1" 404 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/notices.json HTTP/1.1" 404 None
done
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
/ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/osx-arm64/current_repodata.json HTTP/1.1" 200 None
- DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/mai

In [2]:
import numpy as np

In [3]:
A=np.array([1,2,3])
A

array([1, 2, 3])

In [4]:
B=np.array([[1,2],[3,4]])
B

array([[1, 2],
       [3, 4]])

In [5]:
C=np.array([[1,2,3],[4,5,6],[7,8,9]])
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
A1=np.zeros(10)
A1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
A2=np.ones(10)
A2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
A3=np.arange(11)
A3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
A4=np.arange(2,20,3)
A4

array([ 2,  5,  8, 11, 14, 17])

A5=np.empty(5)
A5

In [10]:
A5=np.empty(5) 
A5

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [11]:
A6=np.linspace(0,12,num=5)
A6

array([ 0.,  3.,  6.,  9., 12.])

In [12]:
A7=np.linspace(0,17,num=7)
A7

array([ 0.        ,  2.83333333,  5.66666667,  8.5       , 11.33333333,
       14.16666667, 17.        ])

In [13]:
A8=np.ones(10,dtype=np.int32)
A8

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [14]:
print(C.shape)

(3, 3)


In [15]:
print(C.size)


9


In [16]:
print(C.ndim)

2


In [17]:
A9=np.array([2,4,1,3,7,5,9,6])
print(np.sort(A9))

[1 2 3 4 5 6 7 9]


In [18]:
a=np.array([[1,2,3]])
b=np.array([[4,5,6]])
np.concatenate([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a=np.array([1,2,3,4,5,6])
print(a)
b=np.reshape(a,newshape=[2,3])
print(b)
c=np.reshape(a,newshape=[3,2])
print(c)
d=np.reshape(a,newshape=[6,1])
print(d)
e=np.reshape(a,newshape=[1,6])
print(e)
#f=np.reshape(a,newshape=[2,4])
#print(f) #output:error


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


In [20]:
data=np.array([1,3,5,2,4,8,9,7])
data[3]

2

In [21]:
data[0:3]

array([1, 3, 5])

In [22]:
data[:3]

array([1, 3, 5])

In [23]:
data[1:]

array([3, 5, 2, 4, 8, 9, 7])

In [24]:
data[-2]

9

In [25]:
data[-1:-4:-1]

array([7, 9, 8])

In [26]:
data[::-1]

array([7, 9, 8, 4, 2, 5, 3, 1])

In [27]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[a<7])
a1=a[(a>=3)&(a<7)]
print(a1)
a2=a[(a>=3)|(a<7)]
print(a2)
a3=a[a%2==0]
print(a3)


[1 2 3 4 5 6]
[3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]


In [28]:
import numpy as np
from numpy import linalg as la

In [29]:
x=np.array([[1,2,3],[4,5,6],[2,-3,1]])
x


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 2, -3,  1]])

In [30]:
print(x.T)

[[ 1  4  2]
 [ 2  5 -3]
 [ 3  6  1]]


In [31]:
print(la.inv(x))

[[-0.85185185  0.40740741  0.11111111]
 [-0.2962963   0.18518519 -0.22222222]
 [ 0.81481481 -0.25925926  0.11111111]]


In [32]:
print(la.matrix_power(x,6))

[[ -4725  -4887  -6750]
 [ -8484 -14757 -12984]
 [ -5360   6922  -5843]]


In [33]:
print(np.trace(x))

7


In [34]:
print(la.det(x))

-27.0


In [35]:
print(np.diag(x))

[1 5 1]


In [36]:
A=np.array([[1,2],[3,4]])
x,y=la.eig(A)
print("roots:",x)
print("vectors:",y)

roots: [-0.37228132  5.37228132]
vectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [37]:
print(la.eigvals(A))

[-0.37228132  5.37228132]


In [135]:
import pandas as pd

In [39]:
x=pd.read_csv(r"/Users/teja/Desktop/4_Drug200.csv")
x

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [40]:
print(x.describe())

              Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000


In [41]:
df=x[["Age","Na_to_K"]]
df

Age  Na_to_K
0     23   25.355
1     47   13.093
2     47   10.114
3     28    7.798
4     61   18.043
..   ...      ...
195   56   11.567
196   16   12.006
197   52    9.894
198   23   14.020
199   40   11.349

[200 rows x 2 columns]

In [42]:
print(df.mean())

Age        44.315000
Na_to_K    16.084485
dtype: float64


In [43]:
print(df.median())

Age        45.0000
Na_to_K    13.9365
dtype: float64


In [44]:
print(df.mode())

    Age  Na_to_K
0  47.0   12.006
1   NaN   18.295


In [45]:

print(x.sum())

Age                                                         8863
Sex            FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...
BP             HIGHLOWLOWNORMALLOWNORMALNORMALLOWNORMALLOWLOW...
Cholesterol    HIGHHIGHHIGHHIGHHIGHHIGHHIGHHIGHHIGHNORMALHIGH...
Na_to_K                                                 3216.897
Drug           drugYdrugCdrugCdrugXdrugYdrugXdrugYdrugCdrugYd...
dtype: object


In [46]:
print(x.cumsum())

      Age                                                Sex  \
0      23                                                  F   
1      70                                                 FM   
2     117                                                FMM   
3     145                                               FMMF   
4     206                                              FMMFF   
..    ...                                                ...   
195  8732  FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...   
196  8748  FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...   
197  8800  FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...   
198  8823  FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...   
199  8863  FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...   

                                                    BP  \
0                                                 HIGH   
1                                              HIGHLOW   
2                                           HIGHLOWLOW   

In [47]:
print(x.count())

Age            200
Sex            200
BP             200
Cholesterol    200
Na_to_K        200
Drug           200
dtype: int64


In [48]:
print(x.min())

Age               15
Sex                F
BP              HIGH
Cholesterol     HIGH
Na_to_K        6.269
Drug           drugA
dtype: object


In [49]:
print(x.max())

Age                74
Sex                 M
BP             NORMAL
Cholesterol    NORMAL
Na_to_K        38.247
Drug            drugY
dtype: object


In [50]:
from numpy import cov
covariance=cov(df)
print(covariance)

[[  2.7730125 -39.9254925 -43.433265  ... -49.579815  -10.57395
  -33.7365525]
 [-39.9254925 574.8423245 625.346801  ... 713.844071  152.24243
  485.7347285]
 [-43.433265  625.346801  680.288498  ... 776.560958  165.61814
  528.410393 ]
 ...
 [-49.579815  713.844071  776.560958  ... 886.457618  189.05594
  603.189503 ]
 [-10.57395   152.24243   165.61814   ... 189.05594    40.3202
  128.64299  ]
 [-33.7365525 485.7347285 528.410393  ... 603.189503  128.64299
  410.4399005]]


In [51]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [53]:
from scipy.stats import pearsonr
#data1=x[["Age","Na_to_K"]]
corr=pearsonr(x["Age"],x["Na_to_K"])
print(corr)

PearsonRResult(statistic=-0.06311949726772592, pvalue=0.3745756399034278)


In [54]:
from scipy.stats import spearmanr
data1=x[["Age","Na_to_K"]]
corr,_=spearmanr(data1)
print(corr)

-0.047273882688479915


In [55]:
y=pd.read_csv("/Users/teja/Desktop/1_2015.csv")
y

Country                           Region  Happiness Rank  \
0    Switzerland                   Western Europe               1   
1        Iceland                   Western Europe               2   
2        Denmark                   Western Europe               3   
3         Norway                   Western Europe               4   
4         Canada                    North America               5   
..           ...                              ...             ...   
153       Rwanda               Sub-Saharan Africa             154   
154        Benin               Sub-Saharan Africa             155   
155        Syria  Middle East and Northern Africa             156   
156      Burundi               Sub-Saharan Africa             157   
157         Togo               Sub-Saharan Africa             158   

     Happiness Score  Standard Error  Economy (GDP per Capita)   Family  \
0              7.587         0.03411                   1.39651  1.34951   
1              7.561         0.04884                   1.30232  1.40223   
2              7.527         0.03328                   1.32548  1.36058   
3              7.522         0.03880                   1.45900  1.33095   
4              7.427         0.03553                   1.32629  1.32261   
..               ...             ...                       ...      ...   
153            3.465         0.03464                   0.22208  0.77370   
154            3.340         0.03656                   0.28665  0.35386   
155            3.006         0.05015                   0.66320  0.47489   
156            2.905         0.08658                   0.01530  0.41587   
157            2.839         0.06727                   0.20868  0.13995   

     Health (Life Expectancy)  Freedom  Trust (Government Corruption)  \
0                     0.94143  0.66557                        0.41978   
1                     0.94784  0.62877                        0.14145   
2                     0.87464  0.64938                        0.48357   
3                     0.88521  0.66973                        0.36503   
4                     0.90563  0.63297                        0.32957   
..                        ...      ...                            ...   
153                   0.42864  0.59201                        0.55191   
154                   0.31910  0.48450                        0.08010   
155                   0.72193  0.15684                        0.18906   
156                   0.22396  0.11850                        0.10062   
157                   0.28443  0.36453                        0.10731   

     Generosity  Dystopia Residual  
0       0.29678            2.51738  
1       0.43630            2.70201  
2       0.34139            2.49204  
3       0.34699            2.46531  
4       0.45811            2.45176  
..          ...                ...  
153     0.22628            0.67042  
154     0.18260            1.63328  
155     0.47179            0.32858  
156     0.19727            1.83302  
157     0.16681            1.56726  

[158 rows x 12 columns]

In [56]:
print(y.describe())

       Happiness Rank  Happiness Score  Standard Error  \
count      158.000000       158.000000      158.000000   
mean        79.493671         5.375734        0.047885   
std         45.754363         1.145010        0.017146   
min          1.000000         2.839000        0.018480   
25%         40.250000         4.526000        0.037268   
50%         79.500000         5.232500        0.043940   
75%        118.750000         6.243750        0.052300   
max        158.000000         7.587000        0.136930   

       Economy (GDP per Capita)      Family  Health (Life Expectancy)  \
count                158.000000  158.000000                158.000000   
mean                   0.846137    0.991046                  0.630259   
std                    0.403121    0.272369                  0.247078   
min                    0.000000    0.000000                  0.000000   
25%                    0.545808    0.856823                  0.439185   
50%                    0.910245    1.02

In [57]:
df1=y[["Happiness Rank","Happiness Score","Standard Error","Economy (GDP per Capita)","Family","Health (Life Expectancy)","Freedom","Trust (Government Corruption)","Generosity","Dystopia Residual"]]
df1

Happiness Rank  Happiness Score  Standard Error  \
0                 1            7.587         0.03411   
1                 2            7.561         0.04884   
2                 3            7.527         0.03328   
3                 4            7.522         0.03880   
4                 5            7.427         0.03553   
..              ...              ...             ...   
153             154            3.465         0.03464   
154             155            3.340         0.03656   
155             156            3.006         0.05015   
156             157            2.905         0.08658   
157             158            2.839         0.06727   

     Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                     1.39651  1.34951                   0.94143  0.66557   
1                     1.30232  1.40223                   0.94784  0.62877   
2                     1.32548  1.36058                   0.87464  0.64938   
3                     1.45900  1.33095                   0.88521  0.66973   
4                     1.32629  1.32261                   0.90563  0.63297   
..                        ...      ...                       ...      ...   
153                   0.22208  0.77370                   0.42864  0.59201   
154                   0.28665  0.35386                   0.31910  0.48450   
155                   0.66320  0.47489                   0.72193  0.15684   
156                   0.01530  0.41587                   0.22396  0.11850   
157                   0.20868  0.13995                   0.28443  0.36453   

     Trust (Government Corruption)  Generosity  Dystopia Residual  
0                          0.41978     0.29678            2.51738  
1                          0.14145     0.43630            2.70201  
2                          0.48357     0.34139            2.49204  
3                          0.36503     0.34699            2.46531  
4                          0.32957     0.45811            2.45176  
..                             ...         ...                ...  
153                        0.55191     0.22628            0.67042  
154                        0.08010     0.18260            1.63328  
155                        0.18906     0.47179            0.32858  
156                        0.10062     0.19727            1.83302  
157                        0.10731     0.16681            1.56726  

[158 rows x 10 columns]

In [58]:
print(df1.mean())

Happiness Rank                   79.493671
Happiness Score                   5.375734
Standard Error                    0.047885
Economy (GDP per Capita)          0.846137
Family                            0.991046
Health (Life Expectancy)          0.630259
Freedom                           0.428615
Trust (Government Corruption)     0.143422
Generosity                        0.237296
Dystopia Residual                 2.098977
dtype: float64


In [59]:
print(df1.median())

Happiness Rank                   79.500000
Happiness Score                   5.232500
Standard Error                    0.043940
Economy (GDP per Capita)          0.910245
Family                            1.029510
Health (Life Expectancy)          0.696705
Freedom                           0.435515
Trust (Government Corruption)     0.107220
Generosity                        0.216130
Dystopia Residual                 2.095415
dtype: float64


In [60]:
print(df1.mode())

     Happiness Rank  Happiness Score  Standard Error  \
0              82.0            5.192         0.03751   
1               NaN              NaN         0.03780   
2               NaN              NaN         0.04394   
3               NaN              NaN         0.04934   
4               NaN              NaN         0.05051   
..              ...              ...             ...   
153             NaN              NaN             NaN   
154             NaN              NaN             NaN   
155             NaN              NaN             NaN   
156             NaN              NaN             NaN   
157             NaN              NaN             NaN   

     Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                     0.00000  0.00000                   0.92356  0.00000   
1                     0.01530  0.13995                       NaN  0.07699   
2                     0.01604  0.30285                       NaN  0.09245   
3                  

In [61]:
print(y.sum())

Country                          SwitzerlandIcelandDenmarkNorwayCanadaFinlandNe...
Region                           Western EuropeWestern EuropeWestern EuropeWest...
Happiness Rank                                                               12560
Happiness Score                                                            849.366
Standard Error                                                             7.56579
Economy (GDP per Capita)                                                 133.68968
Family                                                                   156.58526
Health (Life Expectancy)                                                  99.58098
Freedom                                                                   67.72116
Trust (Government Corruption)                                             22.66065
Generosity                                                                37.49269
Dystopia Residual                                                        331.63833
dtyp

In [62]:
print(y.cumsum())

                                               Country  \
0                                          Switzerland   
1                                   SwitzerlandIceland   
2                            SwitzerlandIcelandDenmark   
3                      SwitzerlandIcelandDenmarkNorway   
4                SwitzerlandIcelandDenmarkNorwayCanada   
..                                                 ...   
153  SwitzerlandIcelandDenmarkNorwayCanadaFinlandNe...   
154  SwitzerlandIcelandDenmarkNorwayCanadaFinlandNe...   
155  SwitzerlandIcelandDenmarkNorwayCanadaFinlandNe...   
156  SwitzerlandIcelandDenmarkNorwayCanadaFinlandNe...   
157  SwitzerlandIcelandDenmarkNorwayCanadaFinlandNe...   

                                                Region  Happiness Rank  \
0                                       Western Europe               1   
1                         Western EuropeWestern Europe               3   
2           Western EuropeWestern EuropeWestern Europe               6   
3    We

In [63]:
print(y.count())

Country                          158
Region                           158
Happiness Rank                   158
Happiness Score                  158
Standard Error                   158
Economy (GDP per Capita)         158
Family                           158
Health (Life Expectancy)         158
Freedom                          158
Trust (Government Corruption)    158
Generosity                       158
Dystopia Residual                158
dtype: int64


In [64]:
print(y.min())

Country                                        Afghanistan
Region                           Australia and New Zealand
Happiness Rank                                           1
Happiness Score                                      2.839
Standard Error                                     0.01848
Economy (GDP per Capita)                               0.0
Family                                                 0.0
Health (Life Expectancy)                               0.0
Freedom                                                0.0
Trust (Government Corruption)                          0.0
Generosity                                             0.0
Dystopia Residual                                  0.32858
dtype: object


In [65]:
print(y.max())

Country                                Zimbabwe
Region                           Western Europe
Happiness Rank                              158
Happiness Score                           7.587
Standard Error                          0.13693
Economy (GDP per Capita)                1.69042
Family                                  1.40223
Health (Life Expectancy)                1.02525
Freedom                                 0.66973
Trust (Government Corruption)           0.55191
Generosity                              0.79588
Dystopia Residual                       3.60214
dtype: object


In [66]:
from numpy import cov
covariance=cov(df1)
print(covariance)

[[   4.88841846    4.83879729    4.70142994 ...   -8.94067707
    -8.82138793   -8.98078038]
 [   4.83879729    4.90609656    4.85312686 ...    6.65446601
     6.91187931    6.84394034]
 [   4.70142994    4.85312686    4.92188806 ...   22.31438288
    22.641738     22.68516687]
 ...
 [  -8.94067707    6.65446601   22.31438288 ... 2413.35472621
  2429.10053333 2444.88038009]
 [  -8.82138793    6.91187931   22.641738   ... 2429.10053333
  2445.28647938 2461.11016749]
 [  -8.98078038    6.84394034   22.68516687 ... 2444.88038009
  2461.11016749 2477.06518276]]


In [67]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [75]:
from scipy.stats import pearsonr
#data1=df1
corr=pearsonr(y["Generosity"],y["Dystopia Residual"])
print(corr)

PearsonRResult(statistic=-0.1013011124610882, pvalue=0.2053394437597998)


In [76]:
from scipy.stats import spearmanr
#data1=df1
corr,_=spearmanr(y["Generosity"],y["Dystopia Residual"])
print(corr)

0.008091469045072784


In [77]:
z=pd.read_csv("/Users/teja/Desktop/3_Fitness.csv")
z

SALESMAN    JAN    FEB    MAR    APR    MAY    JUN  TOTAL SALES  \
0             ANU   70.0   80.0   75.0   60.0   72.0   55.0        412.0   
1            BABU   30.0   48.0   35.0   45.0   25.0   37.0        220.0   
2         CHANDRU   65.0   54.0   49.0   54.0   35.0   65.0        322.0   
3           DAVID   85.0   71.0   68.0   77.0   88.0   73.0        462.0   
4        EINSTEIN   55.0   25.0   45.0   50.0   53.0   30.0        258.0   
5          FAROOK   35.0   45.0   15.0   45.0   45.0   25.0        210.0   
6         GOWTHAM   75.0   66.0   59.0   65.0   56.0   30.0        351.0   
7        HARSHITH   29.0   35.0   49.0   48.0   35.0   55.0        247.0   
8          INIYAN   35.0   35.0   50.0   59.0   67.0   73.0        319.0   
9            JOHN   77.0   85.0   77.0   68.0   56.0   25.0        388.0   
10  MONTHLY SALES  556.0  544.0  522.0  571.0  532.0  468.0          NaN   
11            NaN    NaN    NaN    NaN    NaN    NaN    NaN       3189.0   

    Unnamed: 8  Unnamed: 9  Unnamed: 10  \
0          NaN         NaN          NaN   
1          NaN         NaN          NaN   
2          NaN         NaN          NaN   
3          NaN         NaN          NaN   
4          NaN         NaN          NaN   
5          NaN         NaN          NaN   
6          NaN         NaN          NaN   
7          NaN         NaN          NaN   
8          NaN         NaN          NaN   
9          NaN         NaN          NaN   
10      3193.0         NaN          NaN   
11         NaN         NaN          NaN   

                                          Unnamed: 11  
0                                                 NaN  
1                     1. Individual Sales using Sum()  
2   2. Find the pattern trend using conditional fo...  
3   3. Analyze using Pivot table as column percentage  
4                              4. Insert Pivot charts  
5   5. Rank() - returns the rank of a given value ...  
6                                                 NaN  
7                                                  33  
8                                                 NaN  
9                                                 NaN  
10                                                NaN  
11                                                NaN

In [78]:
print(z.describe())

              JAN         FEB         MAR         APR         MAY         JUN  \
count   11.000000   11.000000   11.000000   11.000000   11.000000   11.000000   
mean   101.090909   98.909091   94.909091  103.818182   96.727273   85.090909   
std    152.263886  148.884153  142.770763  155.277054  145.500578  128.347540   
min     29.000000   25.000000   15.000000   45.000000   25.000000   25.000000   
25%     35.000000   40.000000   47.000000   49.000000   40.000000   30.000000   
50%     65.000000   54.000000   50.000000   59.000000   56.000000   55.000000   
75%     76.000000   75.500000   71.500000   66.500000   69.500000   69.000000   
max    556.000000  544.000000  522.000000  571.000000  532.000000  468.000000   

       TOTAL SALES  Unnamed: 8  Unnamed: 9  Unnamed: 10  
count    11.000000         1.0         0.0          0.0  
mean    579.818182      3193.0         NaN          NaN  
std     869.142775         NaN         NaN          NaN  
min     210.000000      3193.0        

In [79]:
df2=z[["JAN","FEB","MAR","APR","MAY","JUN","TOTAL SALES","Unnamed: 8","Unnamed: 9","Unnamed: 10"]]
df2

JAN    FEB    MAR    APR    MAY    JUN  TOTAL SALES  Unnamed: 8  \
0    70.0   80.0   75.0   60.0   72.0   55.0        412.0         NaN   
1    30.0   48.0   35.0   45.0   25.0   37.0        220.0         NaN   
2    65.0   54.0   49.0   54.0   35.0   65.0        322.0         NaN   
3    85.0   71.0   68.0   77.0   88.0   73.0        462.0         NaN   
4    55.0   25.0   45.0   50.0   53.0   30.0        258.0         NaN   
5    35.0   45.0   15.0   45.0   45.0   25.0        210.0         NaN   
6    75.0   66.0   59.0   65.0   56.0   30.0        351.0         NaN   
7    29.0   35.0   49.0   48.0   35.0   55.0        247.0         NaN   
8    35.0   35.0   50.0   59.0   67.0   73.0        319.0         NaN   
9    77.0   85.0   77.0   68.0   56.0   25.0        388.0         NaN   
10  556.0  544.0  522.0  571.0  532.0  468.0          NaN      3193.0   
11    NaN    NaN    NaN    NaN    NaN    NaN       3189.0         NaN   

    Unnamed: 9  Unnamed: 10  
0          NaN          NaN  
1          NaN          NaN  
2          NaN          NaN  
3          NaN          NaN  
4          NaN          NaN  
5          NaN          NaN  
6          NaN          NaN  
7          NaN          NaN  
8          NaN          NaN  
9          NaN          NaN  
10         NaN          NaN  
11         NaN          NaN

In [80]:
print(df2.mean())

JAN             101.090909
FEB              98.909091
MAR              94.909091
APR             103.818182
MAY              96.727273
JUN              85.090909
TOTAL SALES     579.818182
Unnamed: 8     3193.000000
Unnamed: 9             NaN
Unnamed: 10            NaN
dtype: float64


In [81]:
print(df2.median())

JAN              65.0
FEB              54.0
MAR              50.0
APR              59.0
MAY              56.0
JUN              55.0
TOTAL SALES     322.0
Unnamed: 8     3193.0
Unnamed: 9        NaN
Unnamed: 10       NaN
dtype: float64


In [82]:
print(df2.mode())

     JAN   FEB   MAR   APR   MAY   JUN  TOTAL SALES  Unnamed: 8  Unnamed: 9  \
0   35.0  35.0  49.0  45.0  35.0  25.0        210.0      3193.0         NaN   
1    NaN   NaN   NaN   NaN  56.0  30.0        220.0         NaN         NaN   
2    NaN   NaN   NaN   NaN   NaN  55.0        247.0         NaN         NaN   
3    NaN   NaN   NaN   NaN   NaN  73.0        258.0         NaN         NaN   
4    NaN   NaN   NaN   NaN   NaN   NaN        319.0         NaN         NaN   
5    NaN   NaN   NaN   NaN   NaN   NaN        322.0         NaN         NaN   
6    NaN   NaN   NaN   NaN   NaN   NaN        351.0         NaN         NaN   
7    NaN   NaN   NaN   NaN   NaN   NaN        388.0         NaN         NaN   
8    NaN   NaN   NaN   NaN   NaN   NaN        412.0         NaN         NaN   
9    NaN   NaN   NaN   NaN   NaN   NaN        462.0         NaN         NaN   
10   NaN   NaN   NaN   NaN   NaN   NaN       3189.0         NaN         NaN   

    Unnamed: 10  
0           NaN  
1           NaN

In [83]:
print(z.sum())

JAN            1112.0
FEB            1088.0
MAR            1044.0
APR            1142.0
MAY            1064.0
JUN             936.0
TOTAL SALES    6378.0
Unnamed: 8     3193.0
Unnamed: 9        0.0
Unnamed: 10       0.0
dtype: float64


/var/folders/kc/f_2rv2sn30780xky6ysplv4c0000gn/T/ipykernel_2063/3352301598.py:1: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(z.sum())


In [84]:
print(df.cumsum())

      Age   Na_to_K
0      23    25.355
1      70    38.448
2     117    48.562
3     145    56.360
4     206    74.403
..    ...       ...
195  8732  3169.628
196  8748  3181.634
197  8800  3191.528
198  8823  3205.548
199  8863  3216.897

[200 rows x 2 columns]


In [85]:
print(z.count())

SALESMAN       11
JAN            11
FEB            11
MAR            11
APR            11
MAY            11
JUN            11
TOTAL SALES    11
Unnamed: 8      1
Unnamed: 9      0
Unnamed: 10     0
Unnamed: 11     6
dtype: int64


In [86]:
print(z.min())

JAN              29.0
FEB              25.0
MAR              15.0
APR              45.0
MAY              25.0
JUN              25.0
TOTAL SALES     210.0
Unnamed: 8     3193.0
Unnamed: 9        NaN
Unnamed: 10       NaN
dtype: float64


/var/folders/kc/f_2rv2sn30780xky6ysplv4c0000gn/T/ipykernel_2063/496370896.py:1: FutureWarning: The default value of numeric_only in DataFrame.min is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(z.min())


In [87]:
print(z.max())

JAN             556.0
FEB             544.0
MAR             522.0
APR             571.0
MAY             532.0
JUN             468.0
TOTAL SALES    3189.0
Unnamed: 8     3193.0
Unnamed: 9        NaN
Unnamed: 10       NaN
dtype: float64


/var/folders/kc/f_2rv2sn30780xky6ysplv4c0000gn/T/ipykernel_2063/2621443473.py:1: FutureWarning: The default value of numeric_only in DataFrame.max is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(z.max())


In [88]:
from numpy import cov
covariance1=cov(df2)
print(covariance)

[[   4.88841846    4.83879729    4.70142994 ...   -8.94067707
    -8.82138793   -8.98078038]
 [   4.83879729    4.90609656    4.85312686 ...    6.65446601
     6.91187931    6.84394034]
 [   4.70142994    4.85312686    4.92188806 ...   22.31438288
    22.641738     22.68516687]
 ...
 [  -8.94067707    6.65446601   22.31438288 ... 2413.35472621
  2429.10053333 2444.88038009]
 [  -8.82138793    6.91187931   22.641738   ... 2429.10053333
  2445.28647938 2461.11016749]
 [  -8.98078038    6.84394034   22.68516687 ... 2444.88038009
  2461.11016749 2477.06518276]]


In [89]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [97]:
z=z.fillna(z.median())
z

/var/folders/kc/f_2rv2sn30780xky6ysplv4c0000gn/T/ipykernel_2063/2546627403.py:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  z=z.fillna(z.median())


SALESMAN    JAN    FEB    MAR    APR    MAY    JUN  TOTAL SALES  \
0             ANU   70.0   80.0   75.0   60.0   72.0   55.0        412.0   
1            BABU   30.0   48.0   35.0   45.0   25.0   37.0        220.0   
2         CHANDRU   65.0   54.0   49.0   54.0   35.0   65.0        322.0   
3           DAVID   85.0   71.0   68.0   77.0   88.0   73.0        462.0   
4        EINSTEIN   55.0   25.0   45.0   50.0   53.0   30.0        258.0   
5          FAROOK   35.0   45.0   15.0   45.0   45.0   25.0        210.0   
6         GOWTHAM   75.0   66.0   59.0   65.0   56.0   30.0        351.0   
7        HARSHITH   29.0   35.0   49.0   48.0   35.0   55.0        247.0   
8          INIYAN   35.0   35.0   50.0   59.0   67.0   73.0        319.0   
9            JOHN   77.0   85.0   77.0   68.0   56.0   25.0        388.0   
10  MONTHLY SALES  556.0  544.0  522.0  571.0  532.0  468.0        322.0   
11            NaN   65.0   54.0   50.0   59.0   56.0   55.0       3189.0   

    Unnamed: 8  Unnamed: 9  Unnamed: 10  \
0       3193.0         NaN          NaN   
1       3193.0         NaN          NaN   
2       3193.0         NaN          NaN   
3       3193.0         NaN          NaN   
4       3193.0         NaN          NaN   
5       3193.0         NaN          NaN   
6       3193.0         NaN          NaN   
7       3193.0         NaN          NaN   
8       3193.0         NaN          NaN   
9       3193.0         NaN          NaN   
10      3193.0         NaN          NaN   
11      3193.0         NaN          NaN   

                                          Unnamed: 11  
0                                                 NaN  
1                     1. Individual Sales using Sum()  
2   2. Find the pattern trend using conditional fo...  
3   3. Analyze using Pivot table as column percentage  
4                              4. Insert Pivot charts  
5   5. Rank() - returns the rank of a given value ...  
6                                                 NaN  
7                                                  33  
8                                                 NaN  
9                                                 NaN  
10                                                NaN  
11                                                NaN

In [98]:
from scipy.stats import pearsonr
#d2=df2
corr1,_=pearsonr(z["JAN"],z["FEB"])
print(corr1)

0.9956499571685765


In [99]:
from scipy.stats import spearmanr
d2=df2
corr1,_=spearmanr(z["JAN"],z["FEB"])
print(corr1,_)

0.8644366197183098 0.0002859085316708356


In [156]:
z1=pd.read_excel("/Users/teja/Desktop/6_salesworkload.xlsx")
z1

Unnamed: 0  Unnamed: 1      Unnamed: 2 Unnamed: 3  Unnamed: 4 Unnamed: 5  \
0     MonthYear  Time index         Country    StoreID        City    Dept_ID   
1       10.2016           1  United Kingdom      88253  London (I)          1   
2       10.2016           1  United Kingdom      88253  London (I)          2   
3       10.2016           1  United Kingdom      88253  London (I)          3   
4       10.2016           1  United Kingdom      88253  London (I)          4   
...         ...         ...             ...        ...         ...        ...   
7654    06.2017           9          Sweden      29650  Gothenburg         12   
7655    06.2017           9          Sweden      29650  Gothenburg         16   
7656    06.2017           9          Sweden      29650  Gothenburg         11   
7657    06.2017           9          Sweden      29650  Gothenburg         17   
7658    06.2017           9          Sweden      29650  Gothenburg         18   

             Unnamed: 6 Unnamed: 7  Unnamed: 8   Unnamed: 9 Unnamed: 10  \
0            Dept. Name   HoursOwn  HoursLease  Sales units    Turnover   
1                   Dry   3184.764           0       398560     1226244   
2                Frozen   1582.941           0        82725      387810   
3                 other     47.205           0       438400      654657   
4                  Fish   1623.852           0       309425      499434   
...                 ...        ...         ...          ...         ...   
7654           Checkout   6322.323           0      3886530    14538825   
7655  Customer Services   4270.479           0          245           0   
7656           Delivery          0           0            0           0   
7657             others   2224.929           0          245           0   
7658                all    39652.2           0      3886530    15056214   

     Unnamed: 11 Unnamed: 12    Unnamed: 13  
0       Customer   Area (m2)  Opening hours  
1            NaN      953.04         Type A  
2            NaN      720.48         Type A  
3            NaN      966.72         Type A  
4            NaN     1053.36         Type A  
...          ...         ...            ...  
7654         NaN         #NV         Type A  
7655         NaN         #NV         Type A  
7656         NaN         #NV         Type A  
7657         NaN         #NV         Type A  
7658         NaN         #NV         Type A  

[7659 rows x 14 columns]

In [157]:
print(z1.describe())

       Unnamed: 0  Unnamed: 1      Unnamed: 2  Unnamed: 3     Unnamed: 4  \
count        7659        7651            7651        7651           7651   
unique         11          10              12          51             51   
top       10.2016           1  United Kingdom       16927  Barcelona (I)   
freq          850         850             918         153            153   

        Unnamed: 5 Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
count         7651       7651    7651.000        7651        7651   
unique          18         18    3506.000         224        5659   
top              8  Household      47.205           0           0   
freq           450        450     450.000        7172         157   

        Unnamed: 10 Unnamed: 11  Unnamed: 12 Unnamed: 13  
count          7651           1         7651        7651  
unique         5905           1         2827           4  
top               0    Customer            0      Type A  
freq           1480           1      

In [158]:
df3=z1[["Unnamed: 0","Unnamed: 1","Unnamed: 2","Unnamed: 3","Unnamed: 4","Unnamed: 5","Unnamed: 6","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 11","Unnamed: 12","Unnamed: 13"]]
df3

Unnamed: 0  Unnamed: 1      Unnamed: 2 Unnamed: 3  Unnamed: 4 Unnamed: 5  \
0     MonthYear  Time index         Country    StoreID        City    Dept_ID   
1       10.2016           1  United Kingdom      88253  London (I)          1   
2       10.2016           1  United Kingdom      88253  London (I)          2   
3       10.2016           1  United Kingdom      88253  London (I)          3   
4       10.2016           1  United Kingdom      88253  London (I)          4   
...         ...         ...             ...        ...         ...        ...   
7654    06.2017           9          Sweden      29650  Gothenburg         12   
7655    06.2017           9          Sweden      29650  Gothenburg         16   
7656    06.2017           9          Sweden      29650  Gothenburg         11   
7657    06.2017           9          Sweden      29650  Gothenburg         17   
7658    06.2017           9          Sweden      29650  Gothenburg         18   

             Unnamed: 6 Unnamed: 7  Unnamed: 8   Unnamed: 9 Unnamed: 10  \
0            Dept. Name   HoursOwn  HoursLease  Sales units    Turnover   
1                   Dry   3184.764           0       398560     1226244   
2                Frozen   1582.941           0        82725      387810   
3                 other     47.205           0       438400      654657   
4                  Fish   1623.852           0       309425      499434   
...                 ...        ...         ...          ...         ...   
7654           Checkout   6322.323           0      3886530    14538825   
7655  Customer Services   4270.479           0          245           0   
7656           Delivery          0           0            0           0   
7657             others   2224.929           0          245           0   
7658                all    39652.2           0      3886530    15056214   

     Unnamed: 11 Unnamed: 12    Unnamed: 13  
0       Customer   Area (m2)  Opening hours  
1            NaN      953.04         Type A  
2            NaN      720.48         Type A  
3            NaN      966.72         Type A  
4            NaN     1053.36         Type A  
...          ...         ...            ...  
7654         NaN         #NV         Type A  
7655         NaN         #NV         Type A  
7656         NaN         #NV         Type A  
7657         NaN         #NV         Type A  
7658         NaN         #NV         Type A  

[7659 rows x 14 columns]

In [159]:
data3=df3.drop(columns=["Unnamed: 2","Unnamed: 4","Unnamed: 6","Unnamed: 11","Unnamed: 13","Unnamed: 12"])
data3

Unnamed: 0  Unnamed: 1 Unnamed: 3 Unnamed: 5 Unnamed: 7  Unnamed: 8  \
0     MonthYear  Time index    StoreID    Dept_ID   HoursOwn  HoursLease   
1       10.2016           1      88253          1   3184.764           0   
2       10.2016           1      88253          2   1582.941           0   
3       10.2016           1      88253          3     47.205           0   
4       10.2016           1      88253          4   1623.852           0   
...         ...         ...        ...        ...        ...         ...   
7654    06.2017           9      29650         12   6322.323           0   
7655    06.2017           9      29650         16   4270.479           0   
7656    06.2017           9      29650         11          0           0   
7657    06.2017           9      29650         17   2224.929           0   
7658    06.2017           9      29650         18    39652.2           0   

       Unnamed: 9 Unnamed: 10  
0     Sales units    Turnover  
1          398560     1226244  
2           82725      387810  
3          438400      654657  
4          309425      499434  
...           ...         ...  
7654      3886530    14538825  
7655          245           0  
7656            0           0  
7657          245           0  
7658      3886530    15056214  

[7659 rows x 8 columns]

In [160]:
data3=data3.drop(index=0)

In [161]:
data3

Unnamed: 0 Unnamed: 1 Unnamed: 3 Unnamed: 5 Unnamed: 7 Unnamed: 8  \
1       10.2016          1      88253          1   3184.764          0   
2       10.2016          1      88253          2   1582.941          0   
3       10.2016          1      88253          3     47.205          0   
4       10.2016          1      88253          4   1623.852          0   
5       10.2016          1      88253          5   1759.173          0   
...         ...        ...        ...        ...        ...        ...   
7654    06.2017          9      29650         12   6322.323          0   
7655    06.2017          9      29650         16   4270.479          0   
7656    06.2017          9      29650         11          0          0   
7657    06.2017          9      29650         17   2224.929          0   
7658    06.2017          9      29650         18    39652.2          0   

     Unnamed: 9 Unnamed: 10  
1        398560     1226244  
2         82725      387810  
3        438400      654657  
4        309425      499434  
5        165515      329397  
...         ...         ...  
7654    3886530    14538825  
7655        245           0  
7656          0           0  
7657        245           0  
7658    3886530    15056214  

[7658 rows x 8 columns]

In [162]:
print(data3.mean())

Unnamed: 1     5.000000e+00
Unnamed: 3     6.199522e+04
Unnamed: 5     9.470588e+00
Unnamed: 8     2.203608e+01
Unnamed: 9     1.076471e+06
Unnamed: 10    3.721393e+06
dtype: float64


/var/folders/kc/f_2rv2sn30780xky6ysplv4c0000gn/T/ipykernel_2063/3658844921.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(data3.mean())


In [163]:
print(data3.median())

Unnamed: 1          5.0
Unnamed: 3      75400.5
Unnamed: 5          9.0
Unnamed: 8          0.0
Unnamed: 9     293230.0
Unnamed: 10    931957.5
dtype: float64


/var/folders/kc/f_2rv2sn30780xky6ysplv4c0000gn/T/ipykernel_2063/3759872012.py:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(data3.median())


In [164]:
print(data3.mode())

   Unnamed: 0 Unnamed: 1 Unnamed: 3 Unnamed: 5 Unnamed: 7 Unnamed: 8  \
0     01.2017          1      12227          1     47.205          0   
1     02.2017          2      15552          2        NaN        NaN   
2     03.2017          3      16927          3        NaN        NaN   
3     04.2017          4      17647          4        NaN        NaN   
4     05.2017          5      18808          5        NaN        NaN   
5     06.2017          6      19000          6        NaN        NaN   
6     10.2016          7      19340          7        NaN        NaN   
7     11.2016          8      19769          8        NaN        NaN   
8     12.2016          9      20166          9        NaN        NaN   
9         NaN        NaN      20891         11        NaN        NaN   
10        NaN        NaN      22117         12        NaN        NaN   
11        NaN        NaN      23623         13        NaN        NaN   
12        NaN        NaN      29650         14        NaN       

In [165]:
print(data3.sum())

Unnamed: 0     10.201610.201610.201610.201610.201610.201610.2...
Unnamed: 1                                                 38250
Unnamed: 3                                             474263433
Unnamed: 5                                                 72450
Unnamed: 8                                                168576
Unnamed: 9                                            8235000965
Unnamed: 10                                          28468656015
dtype: object


/var/folders/kc/f_2rv2sn30780xky6ysplv4c0000gn/T/ipykernel_2063/1211309486.py:1: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(data3.sum())


In [173]:
data3=data3.fillna(data3.mode())
data3

Unnamed: 0  Unnamed: 1  Unnamed: 3  Unnamed: 5 Unnamed: 7  Unnamed: 8  \
1       10.2016         1.0     88253.0         1.0   3184.764         0.0   
2       10.2016         1.0     88253.0         2.0   1582.941         0.0   
3       10.2016         1.0     88253.0         3.0     47.205         0.0   
4       10.2016         1.0     88253.0         4.0   1623.852         0.0   
5       10.2016         1.0     88253.0         5.0   1759.173         0.0   
...         ...         ...         ...         ...        ...         ...   
7654    06.2017         9.0     29650.0        12.0   6322.323         0.0   
7655    06.2017         9.0     29650.0        16.0   4270.479         0.0   
7656    06.2017         9.0     29650.0        11.0          0         0.0   
7657    06.2017         9.0     29650.0        17.0   2224.929         0.0   
7658    06.2017         9.0     29650.0        18.0    39652.2         0.0   

      Unnamed: 9  Unnamed: 10  
1       398560.0    1226244.0  
2        82725.0     387810.0  
3       438400.0     654657.0  
4       309425.0     499434.0  
5       165515.0     329397.0  
...          ...          ...  
7654   3886530.0   14538825.0  
7655       245.0          0.0  
7656         0.0          0.0  
7657       245.0          0.0  
7658   3886530.0   15056214.0  

[7658 rows x 8 columns]

In [168]:
print(data3.count())

Unnamed: 0     7658
Unnamed: 1     7658
Unnamed: 3     7658
Unnamed: 5     7658
Unnamed: 7     7650
Unnamed: 8     7658
Unnamed: 9     7658
Unnamed: 10    7658
dtype: int64


In [169]:
print(data3.min())

Unnamed: 0      - - - - 
Unnamed: 1           1.0
Unnamed: 3       12227.0
Unnamed: 5           1.0
Unnamed: 8           0.0
Unnamed: 9           0.0
Unnamed: 10          0.0
dtype: object


/var/folders/kc/f_2rv2sn30780xky6ysplv4c0000gn/T/ipykernel_2063/2281988992.py:1: FutureWarning: The default value of numeric_only in DataFrame.min is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(data3.min())


In [170]:
print(data3.max())

Unnamed: 0        12.2016
Unnamed: 1            9.0
Unnamed: 3        98422.0
Unnamed: 5           18.0
Unnamed: 8         3984.0
Unnamed: 9     11242955.0
Unnamed: 10    42717390.0
dtype: object


/var/folders/kc/f_2rv2sn30780xky6ysplv4c0000gn/T/ipykernel_2063/2827393065.py:1: FutureWarning: The default value of numeric_only in DataFrame.max is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(data3.max())


In [259]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [179]:
from scipy.stats import pearsonr
#df3=data3
corr2=pearsonr(data3["Unnamed: 1"],data3["Unnamed: 5"])
print(corr2)

PearsonRResult(statistic=6.7132880820712266e-18, pvalue=1.0000000000000004)


In [181]:
from scipy.stats import spearmanr
#df3=data3
corr2=spearmanr(data3["Unnamed: 1"],data3["Unnamed: 5"])
print(corr2)

SignificanceResult(statistic=0.0, pvalue=1.0)
